name: mega_outlet_app
description: "Mega Outlet - WooCommerce WebView Android App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # WebView
  webview_flutter: 4.2.2

  # State Management
  provider: ^6.1.2

  # Permissions
  permission_handler: ^11.3.1

  # URL Launcher for external browser
  url_launcher: ^6.2.5

  # Shared preferences for settings
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
